language: python
python:
    - "2.7.12"
# command to install dependencies
install:
    - sudo apt-get install mpich
    - pip install python-coveralls
    - pip install coverage
    - pip install -r requirements.txt
    - pip install .
# command to run tests
script:
    - nosetests --with-coverage
branches:
    only:
        - develop
after_success:
    - coveralls                     # upload reports to coveralls.io

